Algoritmo "Exercicio15"
// Disciplina   : [Algoritmos e Programação Estruturada]
// Professor   : Cícero Odilio Cruz
// Descrição   : Exercicio15
// Autor(a)    : Amom
// Data atual  : 06/09/2020
Var
n1: inteiro
n2: inteiro

Inicio
Escreva ("Digite um valor qualquer: ")
Leia (n1)
Se (n1 > 100) e (n1 < 200) entao
     Escreva ("O valor informado de", n1, " está entre 100 e 200")
Senao
     Escreva ("O valor informado de", n1, " não está entre 100 e 200")
FimSe
Fimalgoritmo