Algoritmo "Exercicio01"
// Disciplina   : [Algoritmos e Programação Estruturada]
// Professor   : Cícero Odilio Cruz
// Descrição   : Primeiro exercicio de Portugol
// Autor(a)    : Amom
// Data atual  : 05/09/2020
Var
n1: inteiro
n2: inteiro
n3: inteiro

Inicio
escreva ("Escreva o primeiro valor: ")
leia (n1)
escreva ("Escreva o segundo valor: ")
leia (n2)
n3 <- n1 + n2
Escreva ("O resultado da Soma dos valores é:", n3)
Fimalgoritmo