Algoritmo "Exercicio07"
// Disciplina   : [Algoritmos e Programação Estruturada]
// Professor   : Cícero Odilio Cruz
// Descrição   : Sétimo exercicio
// Autor(a)    : Amom
// Data atual  : 05/09/2020
Var
n1: real
n2: real

Inicio
Escreva ("Qual é a temperatura em graus Celsius é ")
Leia (n1)
n2 <- (9 * n1 + 160)/ 5
Escreval ("A temperatura em Fahrenheit é ", n2:4:2, " graus.")
Fimalgoritmo