Algoritmo "Exercicio18"
// Disciplina   : [Algoritmos e Programação Estruturada]
// Professor   : Cícero Odilio Cruz
// Descrição   : Exercicio18
// Autor(a)    : Amom
// Data atual  : 09/09/2020
Var
idade: inteiro

Inicio
Para idade de 1 ate 75 faca
     Se (idade >= 18) entao
        Escreval ("Pessoa maior de idade com, ", idade, " anos.")
     Senao
        Escreval ("Pessoa menor de idade com, ", idade, " anos.")
     FimSe
FimPara
Fimalgoritmo