Algoritmo "Exercicio17"
// Disciplina   : [Algoritmos e Programação Estruturada]
// Professor   : Cícero Odilio Cruz
// Descrição   : exercicio17
// Autor(a)    : Amom
// Data atual  : 07/09/2020
Var



Inicio
Escreva ("Quer contar até quanto? ")
Leia (Valor)
      Enquanto (Contador <= 150) faca
               EscrevaL (Contador)
               Contador <- contador + 1
      FimEnquanto

Fimalgoritmo