Algoritmo "Exercicio13"
// Disciplina   : [Algoritmos e Programação Estruturada]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Amom
// Data atual  : 06/09/2020
Var
n1: inteiro

Inicio
Escreva ("Digite um número maior ou igual a zero: ")
Leia (n1)
Escreval ("O número informado foi ", n1)
Se (n1 > 10) entao
   Escreval ("Este valor é maior que 10.")
FimSe
Fimalgoritmo