Algoritmo "Exercicio06"
// Disciplina   : [Algoritmos e Programação Estruturada]
// Professor   : Cícero Odilio Cruz
// Descrição   : Exercicio06
// Autor(a)    : Amom
// Data atual  : 09/09/2020
Var
A: inteiro
B: inteiro


Inicio
Escreva ("Digite um número qualquer para o valor A: ")
Leia (A)
Escreva ("Digite um número qualquer para o valor B: ")
Leia (B)
Escreva ("O valor informado para a A foi de, ", B, " e o valor de B foi,", A, ".")

Fimalgoritmo