Algoritmo "Exercicio08"
// Disciplina   : [Algoritmos e Programação Estruturada]
// Professor   : Cícero Odilio Cruz
// Descrição   : Oitavo exercicio
// Autor(a)    : Amom
// Data atual  : 05/09/2020
Var
usd: real
brl: real
brl2: real

Inicio
Escreva ("Informe o valor disponível em doláres: U$ ")
leia (usd)
Escreva ("Infome a cotação do dólar do dia: R$ ")
leia (brl)
brl2 <- usd * brl
Escreva ("O valor convertido para Real é R$ ", brl2)
Fimalgoritmo